name: build

on:
  push: 
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Check Code Format
        run: yarn fmt-check

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
